# Generated by Django 4.0.3 on 2022-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='stock',
            field=models.ManyToManyField(null=True, related_name='classes', to='stock.stock'),
        ),
    ]
