# Generated by Django 4.0.3 on 2022-03-21 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=255)),
                ('expiration', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='stock.stock')),
            ],
        ),
    ]
