# Generated by Django 4.0.3 on 2022-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysis_analyst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='batch',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
