# Generated by Django 4.0.3 on 2022-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysis_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='class_data',
            field=models.JSONField(null=True),
        ),
    ]
