# Generated by Django 4.0.3 on 2022-03-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_class_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='class_data',
        ),
        migrations.AddField(
            model_name='analysis',
            name='class_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
