# Generated by Django 4.0.3 on 2022-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_analysis_class_data_analysis_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='class_data',
            field=models.JSONField(null=True),
        ),
    ]
