# Generated by Django 4.0.3 on 2022-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysis_class_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
