# Generated by Django 4.0.3 on 2022-03-21 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='classes.class')),
            ],
        ),
    ]
