# Generated by Django 4.0.3 on 2022-03-21 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.IntegerField(unique=True)),
                ('minimum', models.CharField(max_length=255)),
                ('maximum', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='class_types.type')),
            ],
        ),
    ]
